version: '3.9'

services:
  flask:
    build:
      dockerfile: ./docker/flask.dockerfile
      context: ./
    ports:
      - 8000:8000

  db:
    build:
      dockerfile: ./docker/postgres.dockerfile
      context: ./

  model:
    image: codait/max-text-summarizer